/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author guede
 */
public class GestionEquipos extends javax.swing.JFrame {

        String user;
        public static int IDEquipo_update = 0;
        DefaultTableModel model = new DefaultTableModel();

        /**
         * Creates new form GestionEquipos
         */
        public GestionEquipos() {
                initComponents();
                user = VentanaLogin.user;

                setLocationRelativeTo(null);
                this.setSize(650, 430);
                this.setResizable(false);
                this.setTitle("Gestion de Equipos. Sesion - " + user);
                this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

                ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
                Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lblWallpaper.getWidth(),
                        lblWallpaper.getHeight(), Image.SCALE_DEFAULT));
                lblWallpaper.setIcon(icono);
                this.repaint();

                tablaEquipos = new JTable(model);
                jScrollPane1.setViewportView(tablaEquipos);

                model.addColumn(" ID# ");
                model.addColumn(" Tipo ");
                model.addColumn("Marca");
                model.addColumn("Estatus");

                try {
                        Connection cn = Conexion.conectar();
                        PreparedStatement pst = cn.prepareStatement(
                                "select id_equipos, tipo_equipo, marca, estatus from equipos");
                        ResultSet rs = pst.executeQuery();

                        while (rs.next()) {
                                Object[] fila = new Object[4];

                                for (int i = 0; i < 4; i++) {
                                        fila[i] = rs.getObject(i + 1);
                                }
                                model.addRow(fila);
                        }
                        cn.close();

                } catch (SQLException e) {
                        System.err.println("Error al obtener datos para la tabla equipos. " + e);
                }
                EscuchaTabla();
        }

        @Override
        public Image getIconImage() {
                Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
                return retValue;
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                boxEstatus = new javax.swing.JComboBox<>();
                jScrollPane1 = new javax.swing.JScrollPane();
                tablaEquipos = new javax.swing.JTable();
                lblFooter = new javax.swing.JLabel();
                botonMostrar = new javax.swing.JButton();
                lblWallpaper = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("Fira Mono", 0, 26)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(197, 224, 224));
                jLabel1.setText("Gestion de Equipos");
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

                boxEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nuevo Ingreso", "En Revision", "Reparado", "No Reparado", "Entregado" }));
                getContentPane().add(boxEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 120, -1));

                tablaEquipos.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane1.setViewportView(tablaEquipos);

                getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 80, 635, 240));

                lblFooter.setForeground(new java.awt.Color(197, 224, 224));
                lblFooter.setText("Creado por Gamer Studio ©");
                getContentPane().add(lblFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

                botonMostrar.setText("Mostrar");
                botonMostrar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                botonMostrarActionPerformed(evt);
                        }
                });
                getContentPane().add(botonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 325, 110, -1));
                getContentPane().add(lblWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
                String estatus = boxEstatus.getSelectedItem().toString();
                String query = "";

                model.setRowCount(0);

                try {
                        Connection cn = Conexion.conectar();

                        if (estatus.equals("Todos")) {
                                query = "select id_equipos, tipo_equipo, marca, estatus from equipos";
                        } else {
                                query = "select id_equipos, tipo_equipo, marca, estatus from equipos where estatus = '" + estatus + "'";
                        }

                        PreparedStatement pst = cn.prepareStatement(query);
                        ResultSet rs = pst.executeQuery();

                        while (rs.next()) {
                                Object[] fila = new Object[4];

                                for (int i = 0; i < 4; i++) {
                                        fila[i] = rs.getObject(i + 1);
                                }
                                model.addRow(fila);
                        }
                        cn.close();

                } catch (SQLException e) {
                        System.err.println("Error al obtener datos para la tabla equipos. " + e);
                }
        }//GEN-LAST:event_botonMostrarActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String[] args) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(GestionEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(GestionEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(GestionEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(GestionEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new GestionEquipos().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton botonMostrar;
        private javax.swing.JComboBox<String> boxEstatus;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lblFooter;
        private javax.swing.JLabel lblWallpaper;
        private javax.swing.JTable tablaEquipos;
        // End of variables declaration//GEN-END:variables

        public void EscuchaTabla() {
                tablaEquipos.addMouseListener(new MouseAdapter() {
                        @Override
                        public void mouseClicked(MouseEvent e) {
                                int fila_point = tablaEquipos.rowAtPoint(e.getPoint());
                                int columna_point = 0;

                                if (fila_point > -1) {
                                        IDEquipo_update = (int) model.getValueAt(fila_point, columna_point);
                                        new FichaEquipoTec().setVisible(true);
                                }
                        }
                });
        }
}
