/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author doug1as
 */
public class NewUser extends javax.swing.JFrame {
    
    String user;

    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
        user = VentanaLogin.user;
        
        this.setTitle("Registro nuevo Usuario. Sesion - " + user);
        this.setSize(650, 430);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lblWallpaper.getWidth(), lblWallpaper.getHeight(), Image.SCALE_DEFAULT));
        lblWallpaper.setIcon(icono);
        repaint();
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txteMail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        boxNiveles = new javax.swing.JComboBox<>();
        txtPass = new javax.swing.JPasswordField();
        lblFooter = new javax.swing.JLabel();
        lblWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(197, 224, 224));
        jLabel1.setText("Registro de Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Fira Sans", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(197, 224, 224));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Fira Sans", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(197, 224, 224));
        jLabel3.setText("eMail:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Fira Sans", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(197, 224, 224));
        jLabel4.setText("Telefono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Fira Sans", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(197, 224, 224));
        jLabel5.setText("Nivel:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Fira Sans", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(197, 224, 224));
        jLabel6.setText("Username:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Fira Sans", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(197, 224, 224));
        jLabel7.setText("Password:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_add_user_info_16706(1).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 234, 120, 100));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 200, -1));
        getContentPane().add(txteMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 200, -1));
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 200, -1));
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 200, -1));

        boxNiveles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedor", "Tecnico" }));
        boxNiveles.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                boxNivelesComponentAdded(evt);
            }
        });
        getContentPane().add(boxNiveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 130, -1));
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 200, -1));

        lblFooter.setForeground(new java.awt.Color(197, 224, 224));
        lblFooter.setText("Creado por Gamer Studio ©");
        getContentPane().add(lblFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));
        getContentPane().add(lblWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxNivelesComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_boxNivelesComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_boxNivelesComponentAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int permisos_box, validacion = 0;
        String nombre, email, telefono, username, pass, permisos_string = "";
        
        email = txteMail.getText().trim();
        nombre = txtNombre.getText().trim();
        telefono = txtPhone.getText().trim();
        username = txtUser.getText().trim();
        pass = txtPass.getText().trim();
        permisos_box = boxNiveles.getSelectedIndex() + 1;
        
        if(email.equals("")){
            txteMail.setBackground(Color.MAGENTA);
            validacion++;
        }
        if(nombre.equals("")){
            txtNombre.setBackground(Color.MAGENTA);
            validacion++;
        }
        if(telefono.equals("")){
            txtPhone.setBackground(Color.MAGENTA);
            validacion++;
        }
        if(username.equals("")){
            txtUser.setBackground(Color.MAGENTA);
            validacion++;
        }
        if(pass.equals("")){
            txtPass.setBackground(Color.MAGENTA);
            validacion++;
        }
        
        if(permisos_box == 1){
            
            permisos_string = "Administrador";
            
        }else if(permisos_box == 2){
            
            permisos_string = "Vendedor";
            
        }else if(permisos_box == 3){
            
            permisos_string = "Tecnico";
            
        }
        
        try {
            
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
            "select username from usuarios where username = '" + username + "'");
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                
                txtUser.setBackground(Color.MAGENTA);
                JOptionPane.showMessageDialog(null, "Nombre de Usuario no disponible.");
                cn.close();
                
            } else {
                
                cn.close();
                
                if (validacion == 0) {
                    
                    try {
                        
                        Connection cn2 = Conexion.conectar();
                        PreparedStatement pst2 = cn2.prepareStatement(
                        "insert into usuarios values (?,?,?,?,?,?,?,?,?)");
                        
                        pst2.setInt(1, 0);
                        pst2.setString(2, nombre);
                        pst2.setString(3, email);
                        pst2.setString(4, telefono);
                        pst2.setString(5, username);
                        pst2.setString(6, pass);
                        pst2.setString(7, permisos_string);
                        pst2.setString(8, "Activo");
                        pst2.setString(9, user);
                        
                        pst2.executeUpdate();
                        cn2.close();
                        
                        Limpiar();
                        
                        txtNombre.setBackground(Color.GREEN);
                        txtPass.setBackground(Color.GREEN);
                        txtPhone.setBackground(Color.GREEN);
                        txtUser.setBackground(Color.GREEN);
                        txteMail.setBackground(Color.GREEN);
                        
                        JOptionPane.showMessageDialog(null, "Registro Exitoso.");
                        
                        this.dispose();
                        
                        
                    } catch (SQLException e) {
                        
                        System.err.println("Error en conectar a la base de datos " + e);
            JOptionPane.showMessageDialog(null, "Error con la base de datos, Contacte al addministrador.");
                        
                    }
                    
                } else {
                    
                    JOptionPane.showMessageDialog(null, "Debe llenar todos los campos requeridos");
                    
                }
                
            }
            
        } catch (SQLException e) {
            System.err.println("Error en validar nombre de usuario " + e);
            JOptionPane.showMessageDialog(null, "Error al comparar Usuario, Contacte al addministrador.");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxNiveles;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblWallpaper;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txteMail;
    // End of variables declaration//GEN-END:variables

    public void Limpiar(){
        
        txtNombre.setText("");
        txtPass.setText("");
        txtPhone.setText("");
        txtUser.setText("");
        txteMail.setText("");
        boxNiveles.setSelectedIndex(0);
        
    }

}
