/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import clases.Conexion;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/**
 *
 * @author doug1as
 */
public class PanelTech extends javax.swing.JFrame {

        String user, nombre_usuario;
        int sesion_usuario;

        /**
         * Creates new form PanelTech
         */
        public PanelTech() {
                initComponents();
                user = VentanaLogin.user;
                sesion_usuario = PanelAdmin.sesion_usuario;

                this.setSize(650, 430);
                this.setResizable(false);
                this.setLocationRelativeTo(null);
                this.setTitle("Panel Tecnico. Sesion  -  " + user);

                if (sesion_usuario == 1) {
                        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
                } else {
                        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
                }
                ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
                Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lblWallpaper.getWidth(),
                        lblWallpaper.getHeight(), Image.SCALE_DEFAULT));
                lblWallpaper.setIcon(icono);
                this.repaint();

                try {
                        Connection cn = Conexion.conectar();
                        PreparedStatement pst = cn.prepareStatement(
                                "select nombre_usuario from usuarios where username = '" + user + "'");
                        ResultSet rs = pst.executeQuery();
                        
                        if (rs.next()) {
                                nombre_usuario = rs.getString("nombre_usuario");
                                lblNombreUsuario.setText("Bienvenido " + nombre_usuario);
                        }
                } catch (SQLException e) {
                        System.err.println("Error al obtener el nombre del usuario");
                }
        }

        @Override
        public Image getIconImage() {
                Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
                return retValue;
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblFooter = new javax.swing.JLabel();
                lblNombreUsuario = new javax.swing.JLabel();
                botonGestionEquipos = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                botonEstatus = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                botonGraficaEquipos = new javax.swing.JButton();
                jLabel3 = new javax.swing.JLabel();
                botonConfigUsuario = new javax.swing.JButton();
                jLabel6 = new javax.swing.JLabel();
                lblWallpaper = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setIconImage(getIconImage());
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lblFooter.setForeground(new java.awt.Color(197, 224, 224));
                lblFooter.setText("Creado por Gamer Studio ©");
                getContentPane().add(lblFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

                lblNombreUsuario.setFont(new java.awt.Font("Fira Sans Book", 1, 18)); // NOI18N
                lblNombreUsuario.setForeground(java.awt.Color.lightGray);
                getContentPane().add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

                botonGestionEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/configure_window_16724.png"))); // NOI18N
                botonGestionEquipos.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                botonGestionEquiposActionPerformed(evt);
                        }
                });
                getContentPane().add(botonGestionEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 120, 100));

                jLabel1.setFont(new java.awt.Font("Fira Sans Book", 1, 16)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(197, 224, 224));
                jLabel1.setText("Gestion de Equipos");
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 167, -1, -1));

                botonEstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reportar.png"))); // NOI18N
                botonEstatus.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                botonEstatusActionPerformed(evt);
                        }
                });
                getContentPane().add(botonEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 120, 100));

                jLabel2.setFont(new java.awt.Font("Fira Sans Book", 1, 16)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(197, 224, 224));
                jLabel2.setText("Grafica de Estatus");
                getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 167, -1, -1));

                botonGraficaEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grafico-circular.png"))); // NOI18N
                botonGraficaEquipos.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                botonGraficaEquiposActionPerformed(evt);
                        }
                });
                getContentPane().add(botonGraficaEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 120, 100));

                jLabel3.setFont(new java.awt.Font("Fira Sans Book", 1, 16)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(197, 224, 224));
                jLabel3.setText("Grafica de Equipos");
                getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 167, -1, -1));

                botonConfigUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/configure_user_16726(1).png"))); // NOI18N
                botonConfigUsuario.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                botonConfigUsuarioActionPerformed(evt);
                        }
                });
                getContentPane().add(botonConfigUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 215, 120, 100));

                jLabel6.setFont(new java.awt.Font("Fira Sans Book", 1, 16)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(197, 224, 224));
                jLabel6.setText("Configurar Usuario");
                getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 322, -1, -1));

                lblWallpaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblWallpaper.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                getContentPane().add(lblWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void botonGestionEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionEquiposActionPerformed
            new GestionEquipos().setVisible(true);
    }//GEN-LAST:event_botonGestionEquiposActionPerformed

    private void botonEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEstatusActionPerformed
            new WorkingOnIt().setVisible(true);
    }//GEN-LAST:event_botonEstatusActionPerformed

    private void botonGraficaEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGraficaEquiposActionPerformed
            new WorkingOnIt().setVisible(true);
    }//GEN-LAST:event_botonGraficaEquiposActionPerformed

        private void botonConfigUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfigUsuarioActionPerformed
                new FichaUsuario().setVisible(true);
        }//GEN-LAST:event_botonConfigUsuarioActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(PanelTech.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(PanelTech.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(PanelTech.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(PanelTech.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new PanelTech().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton botonConfigUsuario;
        private javax.swing.JButton botonEstatus;
        private javax.swing.JButton botonGestionEquipos;
        private javax.swing.JButton botonGraficaEquipos;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel lblFooter;
        private javax.swing.JLabel lblNombreUsuario;
        private javax.swing.JLabel lblWallpaper;
        // End of variables declaration//GEN-END:variables
}
