/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import java.sql.*;
import clases.Conexion;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author doug1as
 */
public class PanelAdmin extends javax.swing.JFrame {
    
    String user, nombre_usuario;
    public static int sesion_usuario;

    /**
     * Creates new form PanelAdmin
     */
    public PanelAdmin() {
        initComponents();
        user = VentanaLogin.user;
        sesion_usuario = 1;
        this.setSize(650, 430);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Panel de Administrador. Sesion - " + user);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lblWallpaper.getWidth(),
                lblWallpaper.getHeight(), Image.SCALE_DEFAULT));
        lblWallpaper.setIcon(icono);
        this.repaint();
        
        try{
            
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
            "select nombre_usuario from usuarios where username = '" + user + "'");
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                
                nombre_usuario = rs.getString("nombre_usuario");
                lblNombreUsuario.setText(nombre_usuario);
                
            }
            
        }catch(SQLException e){
            
            JOptionPane.showMessageDialog(null, "Error en conexion: " + e);
            
        }
        
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegistrarUsuario = new javax.swing.JButton();
        botonGestionUsuario = new javax.swing.JButton();
        botonCreatividad = new javax.swing.JButton();
        botonPanelSales = new javax.swing.JButton();
        botonPanelTech = new javax.swing.JButton();
        botonAcercaDe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblFooter = new javax.swing.JLabel();
        lblWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRegistrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_add_user_16734.png"))); // NOI18N
        botonRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 120, 100));

        botonGestionUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tag_user_card_16777(1).png"))); // NOI18N
        botonGestionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(botonGestionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 120, 100));

        botonCreatividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/person_paper_id_card_profile_user_icon_131800.png"))); // NOI18N
        getContentPane().add(botonCreatividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 120, 100));

        botonPanelSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/support_icon-icons.com_55294.png"))); // NOI18N
        botonPanelSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPanelSalesActionPerformed(evt);
            }
        });
        getContentPane().add(botonPanelSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 215, 120, 100));

        botonPanelTech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/001-worker.png"))); // NOI18N
        botonPanelTech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPanelTechActionPerformed(evt);
            }
        });
        getContentPane().add(botonPanelTech, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 215, 120, 100));

        botonAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signo-de-interrogacion.png"))); // NOI18N
        getContentPane().add(botonAcercaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 215, 120, 100));

        jLabel1.setFont(new java.awt.Font("Fira Sans Book", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(197, 224, 224));
        jLabel1.setText("Agregar Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 167, -1, -1));

        jLabel2.setFont(new java.awt.Font("Fira Sans Book", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(197, 224, 224));
        jLabel2.setText("Informacion Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 167, -1, -1));

        jLabel3.setFont(new java.awt.Font("Fira Sans Book", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(197, 224, 224));
        jLabel3.setText("Creatividad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 167, -1, -1));

        jLabel4.setFont(new java.awt.Font("Fira Sans Book", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(107, 107, 177));
        jLabel4.setText("Panel Ventas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 322, -1, -1));

        jLabel5.setFont(new java.awt.Font("Fira Sans Book", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(107, 107, 177));
        jLabel5.setText("Panel Tecnico");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 322, -1, -1));

        jLabel6.setFont(new java.awt.Font("Fira Sans Book", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(107, 107, 177));
        jLabel6.setText("Acerca de");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 322, -1, -1));

        lblNombreUsuario.setFont(new java.awt.Font("Fira Sans Book", 1, 18)); // NOI18N
        lblNombreUsuario.setForeground(java.awt.Color.lightGray);
        getContentPane().add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblFooter.setText("Creado por Gamer Studio ©");
        getContentPane().add(lblFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));
        getContentPane().add(lblWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarUsuarioActionPerformed
        
        NewUser newuser = new NewUser();
        newuser.setVisible(true);
        
    }//GEN-LAST:event_botonRegistrarUsuarioActionPerformed

    private void botonGestionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionUsuarioActionPerformed
        
        GestionUsuario gestionusuario = new GestionUsuario();
        gestionusuario.setVisible(true);
        
    }//GEN-LAST:event_botonGestionUsuarioActionPerformed

    private void botonPanelSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPanelSalesActionPerformed
        
        PanelSales ventas = new PanelSales();
        ventas.setVisible(true);
        
        
    }//GEN-LAST:event_botonPanelSalesActionPerformed

    private void botonPanelTechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPanelTechActionPerformed
        
        PanelTech tecnico = new PanelTech();
        tecnico.setVisible(true);
        
    }//GEN-LAST:event_botonPanelTechActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAcercaDe;
    private javax.swing.JButton botonCreatividad;
    private javax.swing.JButton botonGestionUsuario;
    private javax.swing.JButton botonPanelSales;
    private javax.swing.JButton botonPanelTech;
    private javax.swing.JButton botonRegistrarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblWallpaper;
    // End of variables declaration//GEN-END:variables
}
