/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import clases.Conexion;
import java.sql.*;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author doug1as
 */
public class PanelSales extends javax.swing.JFrame {

    String user = "", nombre_usuario;
    int sesion_usuario;
    /**
     * Creates new form PanelSales
     */
    public PanelSales() {
        
        initComponents();
        
        user = VentanaLogin.user;
        sesion_usuario = PanelAdmin.sesion_usuario;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(650, 430);
        this.setTitle("Panel de Ventas. - " + user);
        
        if (sesion_usuario == 1) {
            
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            
        } else {
            
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lblWallpaper.getWidth(),
                lblWallpaper.getHeight(), Image.SCALE_DEFAULT));
        lblWallpaper.setIcon(icono);
        this.repaint();
        
        try {
            
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
            "select nombre_usuario from usuarios where username = '" + user + "'");
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                
                nombre_usuario = rs.getString("nombre_usuario");
                lblNombreUsuario.setText("Bienvenido " + nombre_usuario);
                cn.close();
                
            }
            
        } catch (SQLException e) {
            
            JOptionPane.showMessageDialog(null, "Error al consultar nombre en BD\n" + e);
            
        }

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                botonRegistrarCliente = new javax.swing.JButton();
                botonGestionCliente = new javax.swing.JButton();
                botonImprimirClientes = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                lblNombreUsuario = new javax.swing.JLabel();
                lblFooter = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                botonAcercaDe = new javax.swing.JButton();
                lblWallpaper = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setIconImage(getIconImage());
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                botonRegistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_add_user_info_16706(1).png"))); // NOI18N
                botonRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                botonRegistrarClienteActionPerformed(evt);
                        }
                });
                getContentPane().add(botonRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 120, 100));

                botonGestionCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tag_user_card_16777(1).png"))); // NOI18N
                botonGestionCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                botonGestionClienteActionPerformed(evt);
                        }
                });
                getContentPane().add(botonGestionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 120, 100));

                botonImprimirClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document_report_16751.png"))); // NOI18N
                botonImprimirClientes.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                botonImprimirClientesActionPerformed(evt);
                        }
                });
                getContentPane().add(botonImprimirClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 120, 100));

                jLabel1.setFont(new java.awt.Font("Fira Sans Book", 1, 16)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(197, 224, 224));
                jLabel1.setText("Agregar Cliente");
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 167, -1, -1));

                jLabel2.setFont(new java.awt.Font("Fira Sans Book", 1, 16)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(197, 224, 224));
                jLabel2.setText("Informacion Clientes");
                getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 167, -1, -1));

                jLabel3.setFont(new java.awt.Font("Fira Sans Book", 1, 16)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(197, 224, 224));
                jLabel3.setText("Imprimir Clientes");
                getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 167, -1, -1));

                lblNombreUsuario.setFont(new java.awt.Font("Fira Sans Book", 1, 18)); // NOI18N
                lblNombreUsuario.setForeground(java.awt.Color.lightGray);
                getContentPane().add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

                lblFooter.setForeground(new java.awt.Color(197, 224, 224));
                lblFooter.setText("Creado por Gamer Studio ©");
                getContentPane().add(lblFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

                jLabel6.setFont(new java.awt.Font("Fira Sans Book", 1, 16)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(197, 224, 224));
                jLabel6.setText("Configurar Usuario");
                getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 322, -1, -1));

                botonAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/configure_user_16726(1).png"))); // NOI18N
                botonAcercaDe.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                botonAcercaDeActionPerformed(evt);
                        }
                });
                getContentPane().add(botonAcercaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 215, 120, 100));
                getContentPane().add(lblWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarClienteActionPerformed
        NuevoCliente nuevocliente = new NuevoCliente();
        nuevocliente.setVisible(true);
    }//GEN-LAST:event_botonRegistrarClienteActionPerformed

    private void botonGestionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionClienteActionPerformed
        GestionClientes gestionclientes = new GestionClientes();
        gestionclientes.setVisible(true);
    }//GEN-LAST:event_botonGestionClienteActionPerformed

    private void botonImprimirClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImprimirClientesActionPerformed
        Document doc = new Document();
        
        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(doc, new FileOutputStream(ruta + "/Reportes/Clientes/Lista_Clientes.pdf"));
            
            com.itextpdf.text.Image header = com.itextpdf.text.Image.getInstance("src/images/BannerPDF.png");
            header.scaleToFit(650, 1000);
            header.setAlignment(Chunk.ALIGN_CENTER);
            
            Paragraph pf = new Paragraph();
            pf.setAlignment(Paragraph.ALIGN_CENTER);
            pf.add("Lista de Clientes. \n \n");
            pf.setFont(FontFactory.getFont("Tahoma", 18, Font.BOLD, BaseColor.DARK_GRAY));
            
            doc.open();
            doc.add(header);
            doc.add(pf);
            
            PdfPTable tablaClientes = new PdfPTable(5);
            
            tablaClientes.addCell(" ID# ");
            tablaClientes.addCell("Nombre");
            tablaClientes.addCell("eMail");
            tablaClientes.addCell("Telefono");
            tablaClientes.addCell("Direccion");
            
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                "select * from clientes");
                ResultSet rs = pst.executeQuery();
                
                if (rs.next()) {
                    do {                        
                        tablaClientes.addCell(rs.getString(1));
                        tablaClientes.addCell(rs.getString(2));
                        tablaClientes.addCell(rs.getString(3));
                        tablaClientes.addCell(rs.getString(4));
                        tablaClientes.addCell(rs.getString(5));
                    } while (rs.next());
                    doc.add(tablaClientes);
                }
            } catch (SQLException e) {
                System.err.println("Error al generar lista de clientes \n" + e);
            }
            doc.close();
            JOptionPane.showMessageDialog(null, "Lista de Clientes creado correctamente");
            
        } catch (Exception e) {
            System.err.println("Error al generar PDF" + e);
        }        
    }//GEN-LAST:event_botonImprimirClientesActionPerformed

        private void botonAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAcercaDeActionPerformed
                new FichaUsuario().setVisible(true);
        }//GEN-LAST:event_botonAcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelSales().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton botonAcercaDe;
        private javax.swing.JButton botonGestionCliente;
        private javax.swing.JButton botonImprimirClientes;
        private javax.swing.JButton botonRegistrarCliente;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel lblFooter;
        private javax.swing.JLabel lblNombreUsuario;
        private javax.swing.JLabel lblWallpaper;
        // End of variables declaration//GEN-END:variables
}
