/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import java.sql.*;
import clases.Conexion;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author doug1as
 */
public class VentanaLogin extends javax.swing.JFrame {

    public static String user = "";
    String pass = "";

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(400, 550);
        this.setResizable(false);
        this.setTitle("Acceso al Sistema.");
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lblWallpaper.getWidth(),
                lblWallpaper.getHeight(), Image.SCALE_DEFAULT));
        lblWallpaper.setIcon(icono);
        this.repaint();

        ImageIcon wallpaper_logo = new ImageIcon("src/images/DS.png");
        Icon icono_logo = new ImageIcon(wallpaper_logo.getImage().getScaledInstance(lblLogo.getWidth(),
                lblLogo.getHeight(), Image.SCALE_DEFAULT));
        lblLogo.setIcon(icono_logo);
        this.repaint();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                txtUsuario = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                txtPass = new javax.swing.JPasswordField();
                BotonAcceder = new javax.swing.JButton();
                lblFooter = new javax.swing.JLabel();
                lblLogo = new javax.swing.JLabel();
                lblWallpaper = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(0, 0, 255));
                setIconImage(getIconImage());
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("Fira Mono", 1, 18)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(197, 224, 224));
                jLabel1.setText("Usuario:");
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 305, 100, 25));

                txtUsuario.setBackground(new java.awt.Color(153, 153, 255));
                txtUsuario.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
                txtUsuario.setForeground(java.awt.Color.white);
                getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 230, 30));

                jLabel2.setFont(new java.awt.Font("Fira Mono", 1, 18)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(197, 224, 224));
                jLabel2.setText("Password:");
                getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 100, 25));

                txtPass.setBackground(new java.awt.Color(170, 170, 250));
                txtPass.setForeground(new java.awt.Color(255, 255, 255));
                getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 395, 230, 30));

                BotonAcceder.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
                BotonAcceder.setText("Acceder");
                BotonAcceder.setBorder(null);
                BotonAcceder.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BotonAccederActionPerformed(evt);
                        }
                });
                getContentPane().add(BotonAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 445, 120, 35));

                lblFooter.setForeground(new java.awt.Color(197, 224, 224));
                lblFooter.setText("Creado por Gamer Studio ©");
                getContentPane().add(lblFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, -1));
                getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 0, 270, 270));

                lblWallpaper.setBackground(new java.awt.Color(0, 0, 255));
                lblWallpaper.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
                lblWallpaper.setForeground(new java.awt.Color(41, 38, 38));
                getContentPane().add(lblWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void BotonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAccederActionPerformed

        user = txtUsuario.getText().trim();
        pass = txtPass.getText().trim();

        if (!user.equals("") || !pass.equals("")) {

            try {

                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "select tipo_nivel, estatus from usuarios where username = '" + user
                        + "' and password = '" + pass + "'");

                ResultSet rs = pst.executeQuery();
                if (rs.next()) {

                    String nivel = rs.getString("tipo_nivel");
                    String status = rs.getString("estatus");

                    if (nivel.equals("Administrador") && status.equals("Activo")) {

                        dispose();
                        new PanelAdmin().setVisible(true);

                    } else if (nivel.equals("Vendedor") && status.equals("Activo")) {

                        dispose();
                        new PanelSales().setVisible(true);

                    } else if (nivel.equals("Tecnico") && status.equals("Activo")) {

                        dispose();
                        new PanelTech().setVisible(true);

                    }

                } else {

                    JOptionPane.showMessageDialog(null, "Datos de Acceso incorrectos.");
                    txtPass.setText("");
                    txtUsuario.setText("");

                }

            } catch (SQLException e) {
                System.err.println("Error en Acceder: " + e);
                JOptionPane.showMessageDialog(null, "Error al iniciar sesion, contacte al Administrador.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "No dejar campos vacios, intente de nuevo.");
        }

    }//GEN-LAST:event_BotonAccederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton BotonAcceder;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel lblFooter;
        private javax.swing.JLabel lblLogo;
        private javax.swing.JLabel lblWallpaper;
        private javax.swing.JPasswordField txtPass;
        private javax.swing.JTextField txtUsuario;
        // End of variables declaration//GEN-END:variables
}
